name: musa.yml

on:
  push:
    branches:
      - musa
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build code
        run: |
          python build.py
